#!/usr/bin/env node

var fs = require('fs'),
    spawn = require('child_process').spawn,
    resolve = require('./resolve');

if (!fs.existsSync('package.json')) {
    throw new Error('package.json expected');
}

fs.writeFileSync('component.json',
   JSON.stringify(resolve.component(json('package.json'), getOrEmpty('component.json')), null, 2));

fs.writeFileSync('bower.json',
   JSON.stringify(resolve.bower(json('package.json'), getOrEmpty('bower.json')), null, 2));

spawn('git', 'config remote.origin.url'.split(' ')).stdout.on('data', function(data) {
    console.log('need to bower publish?\n\n\tbower register ' +
        json('package.json').name + ' ' +
        data);
});

function getOrEmpty(f) { return fs.existsSync(f) ? json(f) : {}; }
function json(f) { return JSON.parse(fs.readFileSync(f)); }
